version: '3.9'

services:
  web:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
    env_file:
      - .env
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_HOST: db
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - shared-net
    
  # lockgen:
  #   image: ruby:3.3.0
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: bash -c "gem install bundler && bundle install"

volumes:
  shared-pgdata:
    external: true
    name: wishboard_pgdata

networks:
  shared-net:
    external: true
